# Generated by Django 2.2.4 on 2022-02-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='liked_books',
            field=models.ManyToManyField(related_name='books_liked', to='login.User'),
        ),
    ]
